const IMAGES = {
    bar1: require('./img/bar/bar1.jpeg'),
    bar2: require('./img/bar/bar2.jpeg'),
    bar3: require('./img/bar/bar3.jpeg'),
    bar4: require('./img/bar/bar4.jpeg'),
    bar5: require('./img/bar/bar5.jpeg'),
    bar6: require('./img/bar/bar6.jpeg'),
    cadillac1: require('./img/cadillac/cadillac1.jpeg'),
    cadillac2: require('./img/cadillac/cadillac2.jpeg'),
    cadillac3: require('./img/cadillac/cadillac3.jpeg'),
    cadillac4: require('./img/cadillac/cadillac4.jpeg'),
    cadillac5: require('./img/cadillac/cadillac5.jpeg'),
    dimillo1: require('./img/dimillo/dimillo1.jpeg'),
    dimillo2: require('./img/dimillo/dimillo2.jpeg'),
    dimillo3: require('./img/dimillo/dimillo3.jpeg'),
    eventide1: require('./img/eventide/eventide1.jpeg'),
    eventide2: require('./img/eventide/eventide2.jpeg'),
    eventide3: require('./img/eventide/eventide3.jpeg'),
    eventide4: require('./img/eventide/eventide4.jpeg'),
    eventide5: require('./img/eventide/eventide5.jpeg'),
    eventide6: require('./img/eventide/eventide6.jpeg'),
    eventide7: require('./img/eventide/eventide7.jpeg'),
    eventide8: require('./img/eventide/eventide8.jpeg'),
    jordan1: require('./img/jordan/jordan1.jpeg'),
    jordan2: require('./img/jordan/jordan2.jpeg'),
    jordan3: require('./img/jordan/jordan3.jpeg'),
    jordan4: require('./img/jordan/jordan4.jpeg'),
    orchard1: require('./img/orchard/orchard1.jpeg'),
    orchard2: require('./img/orchard/orchard2.jpeg'),
    orchard3: require('./img/orchard/orchard3.jpeg'),
    otter1: require('./img/otter/otter1.jpeg'),
    otter2: require('./img/otter/otter2.jpeg'),
    otter3: require('./img/otter/otter3.jpeg'),
    thompson1: require('./img/thompson/thompson1.jpeg'),
    thompson2: require('./img/thompson/thompson2.jpeg'),
    thompson3: require('./img/thompson/thompson3.jpeg'),
    thompson4: require('./img/thompson/thompson4.jpeg'),
    thompson5: require('./img/thompson/thompson5.jpeg')
}

export default IMAGES;